name: "Windows CI Unit Tests"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-windows:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        nginx:
          - 1.23.2
          - 1.22.1
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: cmd
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
        persist-credentials: false
    - name: Build
      run: .scripts\ci-windows.bat ${{ matrix.nginx }}
    - name: Unit Tests
      run: python -u .scripts\naxsi-windows-test.py ..\nginx-windows\build\dist unit-tests\tests
